### ISSUE TITLE
In classic wotlk prepatch following is no longer possible

### ISSUE THREAD

**Issue by waspoza** [mooreatv/MAMA-multiboxing#14]
I'm getting these errors:
```
[ADDON_ACTION_BLOCKED] AddOn 'Mama' tried to call the protected function 'FollowUnit()'.
[string "@Interface\AddOns\!BugGrabber\BugGrabber.lua"]:519: in function <Interface\AddOns\!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `FollowUnit'
[string "@Interface\AddOns\Mama\Mama-v1.9.3.lua"]:339: in function `ExecuteFollowCommand'
[string "@Interface\AddOns\Mama\Mama-v1.9.3.lua"]:418: in function `ProcessMessage'
[string "@Interface\AddOns\Mama\Mama-v1.9.3.lua"]:445: in function <Interface\AddOns\Mama\Mama.lua:441>
[string "=(tail call)"]: ?
```

**Comment by rodneygauna** [comment]
Looks like the function `FollowUnit()` is now protected - meaning MAMA won't be able to send /follow commands remotely.

Source: https://us.forums.blizzard.com/en/wow/t/classic-addons-still-able-to-execute-remote-follow-commands/1291810

Looks like we'll all need to add a /follow macro for each character and must be pressed on each character screen.

**Comment by mooreatv** [comment]
yes it's addressed in newer release with `/click MamaFollow` and keybindings, thanks
