### ISSUE TITLE
mama to set ema master acording to current party leader

### ISSUE THREAD

**Issue by hexaq2** [mooreatv/MAMA-multiboxing#2]
Ema sets up a master char when first creating the in-game party (not team). This remains 'constant' even if active party leader and follow target is different.

As result, some ema functions (like auto-follow after combat), and other options that depend on 'master' can operate counter to desired ways.

Perhaps mama can inform ema that the master toon has changed to the party leader.

**Comment by hexaq2** [comment]
Found an assignable hotkey inside the wow interface for ema, to assign 'current char to master', in this thread: https://www.dual-boxing.com/threads/55620-EMA-Ebony-s-MultiBoxing-Assistant-Classic-Edition?p=429640&viewfull=1#post429640

Tested it as a ema hotkey and it works correctly, makes you also party leader with the correct option enabled, but is a bit extra hassle. Compared to a 1 click solution, you'd need to also click/enable 'strobe follow leader' hotkey after becoming the master, repeated every time one needs to break follow (i.e some dungeon pulls or such). Overall is 95% there as smoothness.

Would be perfect if one could combine all in a 1 button macro.

**Comment by mooreatv** [comment]
fixed in 0.5.0 (setting ema master with group lead option in config) and also check 0.6.0 for mount/dismount

let me know if you need something else or it doesn't help/work

**Comment by hexaq2** [comment]
Tested the ema master setting it for a few hours last night and it works very well. 
Nice work!
